version: "3"

services:
    abtest:
        build:
            context: .
        volumes:
            - ./:/app:cached
        labels:
            - "traefik.enable=true"
            - "traefik.port=80"
            - "traefik.default.protocol=http"
            - "traefik.frontend.rule=Host:ab-test.localhost"
        networks:
            - landingi

networks:
    landingi:
        external:
            name: devkit_landingi
