name: PHP Composer

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1

        - name: Validate composer.json and composer.lock
          run: composer validate

        - name: Install dependencies
          run: composer install --prefer-dist --no-progress --no-suggest

        - name: Run unit tests
          run: make test

        - name: Run static code analyse tests
          run: make analyze

